--- #YAML:1.0
name:               Net-Twitter-Stream
version:            0.28
abstract:           Connect to the Twitter streaming api
author:
    - Martin Redmond (@martinredmond)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    JSON:          2
    Test::Simple:  0.44
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
